version: "3"
name: "spotify-playlist-janitor"
services:
    db:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
    flyway:
        image: flyway/flyway:latest-alpine
        command: -url=jdbc:postgresql://db/${DB_NAME} -schemas=public -user=${DB_USERNAME} -password=${DB_PASSWORD} -connectRetries=60 migrate
        volumes:
            - ./migrations:/flyway/sql
        depends_on:
            - db
    api:
        build:
            context: ./api
            dockerfile: SpotifyPlaylistJanitorAPI/Dockerfile
        environment:
            ASPNETCORE_URLS: "https://+:5001;http://+:5000"
            # DbConnectionString: "Server=db,5432;Database=SpotifyPlay${DB_NAME}listJanitorDatabase;User Id=${DB_USERNAME};Password=${DB_PASSWORD};"
        ports:
            - 5001:5001
            - 5000:5000
        depends_on:
            - flyway