# This workflow will run the project sql sripts on an empty databse

name: SQL Scripts

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'migrations/**'

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres-service:
        image: postgres
        env:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: postgres_passowrd
          # optional (defaults to `5432`)
          POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # - name: Install sudo package
      #   run: apt update && apt install sudo
      - name: Get SQL Client
        run: sudo apt-get install -y postgresql-client
      - name: Run schema script
        # run: PGPASSWORD=postgres_passowrd psql -f migrations/V1.0__Initial_Schema.sql postgresql://postgres:postgres@127.0.0.1:5432/postgres
        run: PGPASSWORD=postgres_passowrd psql -U postgres -h localhost -p 5432 -d testdb -f migrations/V1.0__Initial_Schema.sql
      - name: Run seed data script
        run: PGPASSWORD=postgres_passowrd psql -f migrations/V1.1__Seed_Data_For_Testing_Ignore_In_Production.sql postgresql://postgres:postgres@127.0.0.1:5432/postgres
