# This workflow will run the project sql sripts on an empty databse

name: SQL Scripts

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'migrations/**'

jobs:
  container-job:
    runs-on: ubuntu-latest
    shell: bash

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Get SQL Client
        run: |
          # for psql
          sudo apt-get install -y postgresql-client
      - name: Run schema script
        run: psql -f migrations/V1.0__Initial_Schema.sql postgresql://postgres:postgres@localhost:5432/postgres
      - name: Run seed data script
        run: psql -f migrations/V1.1__Seed_Data_For_Testing_Ignore_In_Production.sql postgresql://postgres:postgres@localhost:5432/postgres
