# This workflow will run the project sql sripts on an empty databse

name: SQL Scripts

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'migrations/**'

jobs:
  run-postgres-on-ubuntu:
    container: ubuntu
    runs-on: ubuntu-latest

    services:
      postgres-service:
        image: postgres
        env:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: postgres_passowrd
          # optional (defaults to `5432`)
          POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          POSTGRES_USER: postgres_user
        ports:
          - 5433:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Get SQL Client
        run: sudo apt-get install -y postgresql-client
      - name: Run schema script
        # run: psql -f migrations/V1.0__Initial_Schema.sql postgresql://postgres_user:postgres_passowrd@localhost:5432/testdb
        run: PGPASSWORD=postgres_passowrd psql -U postgres_user -h postgres-service -p 5432 -d testdb -f migrations/V1.0__Initial_Schema.sql
      - name: Run seed data script
        run: PGPASSWORD=postgres_passowrd psql -f migrations/V1.1__Seed_Data_For_Testing_Ignore_In_Production.sql postgresql://postgres_user:postgres_passowrd@localhost:5432/testdb
